version: "3.2"

networks:
  predict_net:
    driver: bridge

services:
  api:
    restart: always
    networks:
      - predict_net
    image: predictphp/api:latest
    environment:
        DB_CONNECTION: "mysql"
        DB_HOST: "${DB_HOST}"
        DB_PORT: "${DB_PORT}"
        DB_DATABASE: "${DB_DATABASE}"
        DB_USERNAME: "${DB_USERNAME}"
        DB_PASSWORD: "${DB_PASSWORD}"
        APP_NAME: "Predict API"
        APP_ENV: "local"
        APP_DEBUG: "true"
        APP_URL: "http://localhost:8080"
        APP_TIMEZONE: "America/Los_Angeles"
    # volumes:
      # - ${PWD}/predict-api/routes/:/predict-api/routes/
      # - ${PWD}/predict-api/app/:/predict-api/app/
      # - ${PWD}/predict-api/bootstrap/:/predict-api/bootstrap/
    ports:
      - 8080:80
    depends_on:
      - mysql-seed-client
  mysql-seed-client:
    restart: "no"
    networks:
      - predict_net
    image: predictphp/mariadb-timezone-data:latest
    environment:
       DB_ADDR: "mysql"
       DB_USER: "${DB_USERNAME}"
       DB_NAME: "${DB_DATABASE}"
       SECRET_DB_PASS: "${DB_PASSWORD}"
    entrypoint: /sql/seed-mysql-data.sh
    volumes:
      - ./sql:/sql
    depends_on:
      - mysql
  mysql:
    restart: always
    networks:
      - predict_net
    ports:
      - target: "3306"
        published: "3306"
        protocol: "tcp"
    image: mariadb:latest
    environment:
       MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
       MYSQL_DATABASE: "${DB_DATABASE}"
       MYSQL_USER: "${DB_USERNAME}"
       MYSQL_PASSWORD: "${DB_PASSWORD}"
